---
# nodejs Part
- name: ensure apt key for nodejs is present
  apt_key:
    state: present
    id: 68576280
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"

- name: ensure nodejs apt repo is present
  shell:
  # for setup_11.x 
  curl -sL https://deb.nodesource.com/setup_11.x | bash -
  # for setup_10.x 
  # curl -sL https://deb.nodesource.com/setup_10.x | bash -
  # for setup_8.x 
  # curl -sL https://deb.nodesource.com/setup_8.x | bash -
    
- name: install nodejs package
  package:
    name: nodejs
    state: present
